# Generated by Django 5.2.8 on 2025-12-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetal_app', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('combined_risk_level', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='analysis_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
