# Generated by Django 5.2.8 on 2025-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetal_app', '0005_mlreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlreport',
            name='patient',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('obgyn', 'Obstetrics & Gynecology'), ('mfm', 'Maternal-Fetal Medicine'), ('radiology', 'Radiology'), ('pediatrics', 'Pediatrics'), ('prenatal_counselling', 'Prenatal Counselling')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mlreport',
            name='confidence',
            field=models.IntegerField(),
        ),
    ]
